sign,verify

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -95,38 +95,31 @@ jobs:
           echo ${{ github.event.pull_request.head.sha || github.sha }}
           echo ${{ github.event.pull_request.head.sha }}
 
-      - uses: actions/download-artifact@v2
-        if: "contains(github.event.head_commit.message, 'verify')"
+      # - uses: actions/download-artifact@v2
+      #   if: "contains(github.event.head_commit.message, 'verify')"
+      #   with:
+      #     name: bomber-signatures
+
+      - name: SIGN - Bomber attest src again
+        if: "contains(github.event.head_commit.message, 'sign')"
+        id: bomber_attest
+        uses: scribe-security/bomber-action/bomb-syft@v20
         with:
-          name: bomber-signatures
+           type: dir
+           target: /github/workspace/
+           verbose: 3
+           format: attest
+           attest-name: checkout
+           attest-config: config/.cocosign.yaml
 
-      # - name: VERIFY - Wait for sign checkout
-      #   uses: fountainhead/action-wait-for-check@v1.0.0
-      #   id: wait-checkout-sign
-      #   with:
-      #     token: ${{ secrets.GITHUB_TOKEN }}
-      #     checkName: "checkout-sign"
-      #     ref: ${{ github.event.pull_request.head.sha || github.sha }}
-      #     timeoutSeconds: 120
-      #     intervalSeconds: 10
-
-      # - name: VERIFY - Fail cli
-      #   if: steps.cli-test.outputs.conclusion != 'success'
-      #   run: exit 1
-
-      # - name: VERIFY - Restore checkout signatures cache
-      #   id: checkout-sign-cache
-      #   uses: actions/cache@v2
-      #   with:
-      #     path: bomber_reports
-      #     key: checkout-${{ github.sha }}
-
-      # - name: VERIFY - Read checkout signature from cache
-      #   if: steps.checkout-sign-cache.outputs.cache-hit != 'true' && contains(github.event.head_commit.message, 'verify')
-      #   uses: actions/github-script@v3
-      #   with:
-      #     script: |
-      #         core.setFailed('Signature should be present in cache')
+      - name: SIGN - Archive bomber signature
+        if: "contains(github.event.head_commit.message, 'sign')"
+        uses: actions/upload-artifact@v2
+        with:
+          name: bomber-signatures-build
+          path: |
+            bomber_reports
+          retention-days: 1
 
       - name: VERIFY - Bomber verify checkout
         if: "contains(github.event.head_commit.message, 'verify')"
@@ -137,7 +130,7 @@ jobs:
            target: /github/workspace/
            verbose: 3
            attest-name: checkout
-           attest-config: .github/workflows/fixtures/.cocosign.yaml
+           attest-config: config/.cocosign.yaml
 
       - name: Set up Go
         uses: actions/setup-go@v2
@@ -307,3 +300,42 @@ jobs:
             ./release.yaml
             ./build_image.tar
           retention-days: 1
+
+
+
+
+
+
+
+
+
+
+
+
+      # - name: VERIFY - Wait for sign checkout
+      #   uses: fountainhead/action-wait-for-check@v1.0.0
+      #   id: wait-checkout-sign
+      #   with:
+      #     token: ${{ secrets.GITHUB_TOKEN }}
+      #     checkName: "checkout-sign"
+      #     ref: ${{ github.event.pull_request.head.sha || github.sha }}
+      #     timeoutSeconds: 120
+      #     intervalSeconds: 10
+
+      # - name: VERIFY - Fail cli
+      #   if: steps.cli-test.outputs.conclusion != 'success'
+      #   run: exit 1
+
+      # - name: VERIFY - Restore checkout signatures cache
+      #   id: checkout-sign-cache
+      #   uses: actions/cache@v2
+      #   with:
+      #     path: bomber_reports
+      #     key: checkout-${{ github.sha }}
+
+      # - name: VERIFY - Read checkout signature from cache
+      #   if: steps.checkout-sign-cache.outputs.cache-hit != 'true' && contains(github.event.head_commit.message, 'verify')
+      #   uses: actions/github-script@v3
+      #   with:
+      #     script: |
+      #         core.setFailed('Signature should be present in cache')
